name: app_environment
channels:
  - snowflake
dependencies:
  - langchain=*
  - langchain-experimental=*
  - langchain-text-splitters=*
  - snowflake-ml-python=*
  - snowflake-snowpark-python=*
  - snowflake.core=*
